[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
terra_registry = "GaEDbktvpZ3qiqp4PmFgHwDSa6JsFfVjXFqNb2nTbage"

[programs.localnet]
terra_registry = "GaEDbktvpZ3qiqp4PmFgHwDSa6JsFfVjXFqNb2nTbage"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/terra_registry"]

[hooks]

[test]
startup_wait = 10000
shutdown_wait = 2000
upgradeable = false
