export type BackendMethod = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE'

export interface BackendOperation {
  id: string
  group: string
  method: BackendMethod
  path: string
  summary: string
  query?: string
  body?: string
  sensitive?: boolean
  disabledReason?: string
  mutates?: boolean
}

export const BACKEND_OPERATIONS: BackendOperation[] = [
  { id: 'health', group: 'System', method: 'GET', path: '/health', summary: 'API and database health' },
  { id: 'activity', group: 'Activity', method: 'GET', path: '/activity', summary: 'Recent API-side activity', body: undefined },
  { id: 'demo-catalog', group: 'Demo scenarios', method: 'GET', path: '/demo/scenarios', summary: 'Available deterministic scenarios' },
  { id: 'demo-run', group: 'Demo scenarios', method: 'POST', path: '/demo/scenarios/:name', summary: 'Run a deterministic scenario', body: '{"seed":"terra-preview"}', mutates: false },
  { id: 'parcels-list', group: 'Parcels', method: 'GET', path: '/parcels', summary: 'List mapped parcels', query: '{"minx":11.49,"miny":3.84,"maxx":11.52,"maxy":3.86}' },
  { id: 'parcels-get', group: 'Parcels', method: 'GET', path: '/parcels/:id', summary: 'Read one mapped parcel' },
  { id: 'parcels-create', group: 'Parcels', method: 'POST', path: '/parcels', summary: 'Register off-chain parcel geometry', body: '{"name":"Example parcel","holder":"wallet-address","status":"registered","geometry":{"type":"Polygon","coordinates":[[[11.5,3.8],[11.501,3.8],[11.501,3.801],[11.5,3.801],[11.5,3.8]]]}}' },
  { id: 'parcels-delete', group: 'Parcels', method: 'DELETE', path: '/parcels/:id', summary: 'Delete an off-chain parcel', sensitive: true },
  { id: 'parcels-reconcile', group: 'Parcels', method: 'POST', path: '/parcels/:id/reconcile', summary: 'Reconcile parcel mirror with authority', sensitive: true },
  { id: 'parcels-forfeiture', group: 'Parcels', method: 'POST', path: '/parcels/:id/forfeiture', summary: 'Submit court-authorized forfeiture', body: '{"caseHash":"<64-hex>","newOwner":"<wallet>","threshold":2,"validators":["<validator>"],"relayer":"<authority-wallet>"}', sensitive: true },
  { id: 'disputes-file', group: 'Disputes', method: 'POST', path: '/parcels/:id/disputes', summary: 'File a parcel dispute', body: '{"case_hash":"<64-hex>","required":2,"validators":["<validator>"],"filer":"<wallet>"}' },
  { id: 'parcel-right-renew', group: 'Rights', method: 'POST', path: '/parcels/:parcel_id/rights/:nonce/renew', summary: 'Renew a time-bound right', body: '{"new_expires_at":"2030-01-01T00:00:00Z","new_notes":"","holder":"<wallet>","granter":"<wallet>"}' },
  { id: 'parcel-right-sweep', group: 'Rights', method: 'POST', path: '/parcels/:parcel_id/rights/:nonce/sweep', summary: 'Sweep an expired right', body: '{"keeper":"<wallet>"}', sensitive: true },
  { id: 'rights-renew', group: 'Rights', method: 'POST', path: '/rights/:parcel_id/:nonce/renew', summary: 'Renew a time-bound right using the rights route', body: '{"new_expires_at":"2030-01-01T00:00:00Z","new_notes":"","holder":"<wallet>","granter":"<wallet>"}' },
  { id: 'rights-sweep', group: 'Rights', method: 'POST', path: '/rights/:parcel_id/:nonce/sweep', summary: 'Sweep an expired right using the rights route', body: '{"keeper":"<wallet>"}', sensitive: true },
  { id: 'identity-bind', group: 'Identity & recovery', method: 'POST', path: '/identities', summary: 'Identity binding (requires wallet message signature)', body: '{"identity_hash":"<64-hex>","owner":"<wallet>","recovery":"<recovery-wallet>"}', sensitive: true },
  { id: 'identity-get', group: 'Identity & recovery', method: 'GET', path: '/identities/:wallet', summary: 'Read wallet identity' },
  { id: 'succession-request', group: 'Identity & recovery', method: 'POST', path: '/identities/:identity_hash/successions', summary: 'Request succession or guardianship', body: '{"successor":"<wallet>","kind":0,"validators":["<validator>"]}' },
  { id: 'succession-cancel', group: 'Identity & recovery', method: 'POST', path: '/identities/:identity_hash/successions/:successor/cancel', summary: 'Cancel a succession request', sensitive: true },
  { id: 'succession-claim', group: 'Identity & recovery', method: 'POST', path: '/identities/:identity_hash/successions/:successor/claim', summary: 'Claim an eligible succession', sensitive: true },
  { id: 'succession-endorse', group: 'Identity & recovery', method: 'POST', path: '/identities/:identity_hash/successions/:successor/endorsement', summary: 'Endorse a succession request', body: '{"validator":"<wallet>"}' },
  { id: 'guardianship-revoke', group: 'Identity & recovery', method: 'POST', path: '/identities/:identity_hash/revoke-guardianship', summary: 'Revoke guardianship', body: '{"new_owner":"<wallet>","revoked_by":"<wallet>"}', sensitive: true },
  { id: 'authority-list', group: 'Authority registry', method: 'GET', path: '/authority-registry', summary: 'List authority registries' },
  { id: 'authority-create', group: 'Authority registry', method: 'POST', path: '/authority-registry', summary: 'Create authority registry', body: '{"pubkey":"<registry>","admin":"<wallet>","validators":["<validator>"]}', sensitive: true },
  { id: 'authority-get', group: 'Authority registry', method: 'GET', path: '/authority-registry/:pubkey', summary: 'Read authority registry' },
  { id: 'authority-add-validator', group: 'Authority registry', method: 'POST', path: '/authority-registry/:pubkey/validators', summary: 'Nominate a validator', body: '{"validator":"<wallet>"}', sensitive: true },
  { id: 'authority-remove-validator', group: 'Authority registry', method: 'DELETE', path: '/authority-registry/:pubkey/validators/:validator', summary: 'Remove validator', sensitive: true },
  { id: 'authority-endorse', group: 'Authority registry', method: 'POST', path: '/authority-registry/:pubkey/endorsements', summary: 'Endorse validator nomination', body: '{"validator":"<wallet>"}', sensitive: true },
  { id: 'vault-list', group: 'Vaults', method: 'GET', path: '/vaults', summary: 'List encrypted vault metadata' },
  { id: 'vault-create', group: 'Vaults', method: 'POST', path: '/vaults', summary: 'Register encrypted vault metadata', body: '{"subject_pubkey":"<wallet>","ciphertext_cid":"<cid>","ciphertext_hash":"<hash>","algorithm_id":1,"storage_uris":[],"shard_holders":["<wallet>"],"threshold":1}' },
  { id: 'vault-get', group: 'Vaults', method: 'GET', path: '/vaults/:vault_pubkey', summary: 'Read vault metadata' },
  { id: 'vault-access', group: 'Vaults', method: 'POST', path: '/vaults/:vault_pubkey/access', summary: 'Record time-bounded vault access authorization', body: '{"authority":"<wallet>","purpose":"<purpose>","expiry":"2030-01-01T00:00:00Z","nonce":"<nonce>"}', sensitive: true },
  { id: 'vault-rotation', group: 'Vaults', method: 'POST', path: '/vaults/:vault_pubkey/rotations', summary: 'Initiate shard rotation', body: '{"initiator":"<wallet>","old_ciphertext_hash":"<hash>","new_ciphertext_hash":"<hash>","new_shard_holders":["<wallet>"],"new_threshold":1}', sensitive: true },
  { id: 'vault-endorse-rotation', group: 'Vaults', method: 'POST', path: '/vaults/:vault_pubkey/rotations/:rotation_pubkey/endorse', summary: 'Endorse shard rotation', body: '{"validator":"<wallet>"}', sensitive: true },
  { id: 'vault-execute-rotation', group: 'Vaults', method: 'POST', path: '/vaults/:vault_pubkey/rotations/:rotation_pubkey/execute', summary: 'Execute shard rotation', sensitive: true },
  { id: 'vault-cancel-rotation', group: 'Vaults', method: 'POST', path: '/vaults/:vault_pubkey/rotations/:rotation_pubkey/cancel', summary: 'Cancel shard rotation', sensitive: true },
  { id: 'vault-ping', group: 'Vaults', method: 'POST', path: '/vaults/:vault_pubkey/ping', summary: 'Record shard availability ping', body: '{"validator":"<wallet>"}' },
  { id: 'vault-access-logs', group: 'Vaults', method: 'GET', path: '/vaults/:vault_pubkey/access-logs', summary: 'Read vault access log' },
  { id: 'disputes-list', group: 'Disputes', method: 'GET', path: '/disputes', summary: 'List disputes' },
  { id: 'disputes-get', group: 'Disputes', method: 'GET', path: '/disputes/:id', summary: 'Read dispute' },
  { id: 'disputes-freeze', group: 'Disputes', method: 'POST', path: '/disputes/:id/freeze', summary: 'Freeze disputed parcel', sensitive: true },
  { id: 'disputes-adjudicate', group: 'Disputes', method: 'POST', path: '/disputes/:id/adjudicate', summary: 'Adjudicate dispute', body: '{"outcome":"owner_wins","authority":"<authority-wallet>"}', sensitive: true },
  { id: 'disputes-execute', group: 'Disputes', method: 'POST', path: '/disputes/:id/execute', summary: 'Execute dispute judgment', sensitive: true },
  { id: 'disputes-cancel', group: 'Disputes', method: 'DELETE', path: '/disputes/:id', summary: 'Cancel dispute', sensitive: true },
  { id: 'escrows-list', group: 'Escrows', method: 'GET', path: '/escrows', summary: 'List escrow records' },
  { id: 'escrows-create', group: 'Escrows', method: 'POST', path: '/escrows', summary: 'Create escrow record', body: '{"parcel_id":"<parcel-id>","seller":"<wallet>","buyer":"<wallet>","amount":1}' },
  { id: 'escrows-get', group: 'Escrows', method: 'GET', path: '/escrows/:id', summary: 'Read escrow record' },
  { id: 'escrows-deposit', group: 'Escrows', method: 'POST', path: '/escrows/:id/deposit', summary: 'Record escrow deposit', body: '{"escrow_id":"<id>","buyer":"<wallet>","deposit_amount":1}', sensitive: true },
  { id: 'escrows-accept', group: 'Escrows', method: 'POST', path: '/escrows/:id/accept', summary: 'Accept escrow', body: '{"seller":"<wallet>"}', sensitive: true },
  { id: 'escrows-settle', group: 'Escrows', method: 'POST', path: '/escrows/:id/settle', summary: 'Settle escrow', body: '{"settler":"<wallet>"}', sensitive: true },
  { id: 'escrows-cancel', group: 'Escrows', method: 'POST', path: '/escrows/:id/cancel', summary: 'Cancel escrow', body: '{"canceller":"<wallet>","buyer":"<wallet>"}', sensitive: true },
  { id: 'escrows-dispute', group: 'Escrows', method: 'POST', path: '/escrows/:id/dispute', summary: 'Mark escrow as disputed', body: '{"case_hash":"<64-hex>","required":2,"validators":["<validator>"],"filer":"<wallet>"}', sensitive: true },
  { id: 'escrows-expire', group: 'Escrows', method: 'POST', path: '/escrows/:id/expire', summary: 'Expire escrow', body: '{"caller":"<wallet>"}', sensitive: true },
  { id: 'rights-list', group: 'Rights', method: 'GET', path: '/rights', summary: 'List time-bound rights' },
  { id: 'rights-get', group: 'Rights', method: 'GET', path: '/rights/:id', summary: 'Read right record' },
  { id: 'rights-by-parcel', group: 'Rights', method: 'GET', path: '/rights/parcel/:parcel_id', summary: 'List rights on parcel' },
  { id: 'rights-conditional', group: 'Rights', method: 'POST', path: '/rights/conditional', summary: 'Grant conditional right', body: '{"parcel_id":"<parcel-id>","nonce":0,"rights_kind":"usage","holder":"<wallet>","expires_at":null,"condition_deadline":"2030-01-01T00:00:00Z","condition_desc":"<condition>","grace_period_secs":0,"notes":""}', sensitive: true },
  { id: 'cross-border-jurisdictions', group: 'Cross-border identity', method: 'GET', path: '/cross-border/jurisdictions', summary: 'List jurisdictions' },
  { id: 'cross-border-register', group: 'Cross-border identity', method: 'POST', path: '/cross-border/jurisdictions', summary: 'Register jurisdiction', body: '{"country_code":"CM","authority":"<wallet>","jurisdiction_name":"<name>","credential_schema_cid":"<cid>","revocation_registry":"<registry>","verification_key_hash":"<hash>","algorithm_id":1}', sensitive: true },
  { id: 'cross-border-get-jurisdiction', group: 'Cross-border identity', method: 'GET', path: '/cross-border/jurisdictions/:id', summary: 'Read jurisdiction' },
  { id: 'cross-border-update-jurisdiction', group: 'Cross-border identity', method: 'PATCH', path: '/cross-border/jurisdictions/:id', summary: 'Update jurisdiction', body: '{"status":"active"}', sensitive: true },
  { id: 'cross-border-bindings', group: 'Cross-border identity', method: 'GET', path: '/cross-border/bindings', summary: 'List identity bindings' },
  { id: 'cross-border-bind', group: 'Cross-border identity', method: 'POST', path: '/cross-border/bindings', summary: 'Bind cross-border identity', body: '{"jurisdiction_id":"<id>","identity_hash":"<hash>","credential_commitment":"<commitment>","proof_data":"<proof>","nullifier_nonce":"<nonce>","expires_at":null}', sensitive: true },
  { id: 'cross-border-get-binding', group: 'Cross-border identity', method: 'GET', path: '/cross-border/bindings/:id', summary: 'Read identity binding' },
  { id: 'cross-border-verify', group: 'Cross-border identity', method: 'POST', path: '/cross-border/bindings/:id/verify', summary: 'Verify membership', body: '{"validator":"<wallet>"}', sensitive: true },
  { id: 'cross-border-revoke', group: 'Cross-border identity', method: 'POST', path: '/cross-border/bindings/:id/revoke', summary: 'Revoke identity binding', body: '{"reason":"<reason>"}', sensitive: true },
  { id: 'cross-border-rebind', group: 'Cross-border identity', method: 'POST', path: '/cross-border/bindings/:id/rebind', summary: 'Rebind identity credential', body: '{"credential_commitment":"<commitment>","proof_data":"<proof>","nullifier_nonce":"<nonce>","expires_at":null}', sensitive: true },
  { id: 'subdivisions-list', group: 'Subdivision & amalgamation', method: 'GET', path: '/subdivision/subdivisions', summary: 'List subdivision records' },
  { id: 'subdivisions-create', group: 'Subdivision & amalgamation', method: 'POST', path: '/subdivision/subdivisions', summary: 'Create subdivision record', body: '{"original_parcel_id":"<id>","sub_parcel_id":"<id>","original_geometry_hash":"<hash>","new_geometry_hash":"<hash>","initiated_by":"<wallet>"}' },
  { id: 'subdivisions-get', group: 'Subdivision & amalgamation', method: 'GET', path: '/subdivision/subdivisions/:id', summary: 'Read subdivision' },
  { id: 'subdivisions-update', group: 'Subdivision & amalgamation', method: 'PATCH', path: '/subdivision/subdivisions/:id', summary: 'Update subdivision workflow', body: '{"rights_migrated":true,"status":"completed"}', sensitive: true },
  { id: 'amalgamations-list', group: 'Subdivision & amalgamation', method: 'GET', path: '/subdivision/amalgamations', summary: 'List amalgamation records' },
  { id: 'amalgamations-create', group: 'Subdivision & amalgamation', method: 'POST', path: '/subdivision/amalgamations', summary: 'Create amalgamation record', body: '{"result_parcel_id":"<id>","source_parcel_id":"<id>","source_geometry_hash":"<hash>","result_geometry_hash":"<hash>","initiated_by":"<wallet>"}' },
  { id: 'amalgamations-get', group: 'Subdivision & amalgamation', method: 'GET', path: '/subdivision/amalgamations/:id', summary: 'Read amalgamation' },
  { id: 'amalgamations-update', group: 'Subdivision & amalgamation', method: 'PATCH', path: '/subdivision/amalgamations/:id', summary: 'Update amalgamation workflow', body: '{"rights_merged":true,"status":"completed"}', sensitive: true },
  { id: 'staking-pools', group: 'Staking & slashing', method: 'GET', path: '/staking/pools', summary: 'List stake pools' },
  { id: 'staking-pool-create', group: 'Staking & slashing', method: 'POST', path: '/staking/pools', summary: 'Create stake pool mirror record', body: '{"stake_pool_address":"<address>","region_registry_address":"<address>","reward_rate_bps":100}', sensitive: true },
  { id: 'staking-pool-get', group: 'Staking & slashing', method: 'GET', path: '/staking/pools/:address', summary: 'Read stake pool' },
  { id: 'staking-pool-update', group: 'Staking & slashing', method: 'PUT', path: '/staking/pools/:address', summary: 'Update stake pool mirror record', body: '{"reward_rate_bps":100}', sensitive: true },
  { id: 'staking-stakes', group: 'Staking & slashing', method: 'GET', path: '/staking/stakes', summary: 'List validator stakes' },
  { id: 'staking-stake-create', group: 'Staking & slashing', method: 'POST', path: '/staking/stakes', summary: 'Create validator stake mirror record', body: '{"validator_stake_address":"<address>","stake_pool_address":"<address>","validator_address":"<address>"}', sensitive: true },
  { id: 'staking-stake-get', group: 'Staking & slashing', method: 'GET', path: '/staking/stakes/:address', summary: 'Read validator stake' },
  { id: 'staking-stake-update', group: 'Staking & slashing', method: 'PUT', path: '/staking/stakes/:address', summary: 'Update validator stake mirror record', body: '{"staked_lamports":0}', sensitive: true },
  { id: 'staking-reports', group: 'Staking & slashing', method: 'GET', path: '/staking/reports', summary: 'List slashing reports' },
  { id: 'staking-report-create', group: 'Staking & slashing', method: 'POST', path: '/staking/reports', summary: 'File slashing report', body: '{"slashing_report_address":"<address>","stake_pool_address":"<address>","reporter_address":"<wallet>","evidence_hash":"<hash>","offender_address":"<wallet>","offense_type":0,"offense_details":"<details>","reporter_bond_lamports":0,"appeal_deadline":"2030-01-01T00:00:00Z"}', sensitive: true },
  { id: 'staking-report-get', group: 'Staking & slashing', method: 'GET', path: '/staking/reports/:address', summary: 'Read slashing report' },
  { id: 'staking-report-update', group: 'Staking & slashing', method: 'PUT', path: '/staking/reports/:address', summary: 'Update slashing report', body: '{"status":1}', sensitive: true },
  { id: 'zk-zones', group: 'ZK ownership', method: 'GET', path: '/zk', summary: 'List ownership zone sets' },
  { id: 'zk-register', group: 'ZK ownership', method: 'POST', path: '/zk', summary: 'Register ownership zone set', body: '{"zone_set_address":"<address>","zone_id":"<zone>","authority":"<wallet>","snapshot_cid":"<cid>","snapshot_hash":"<hash>","root_address":"<address>","merkle_root":"<root>"}', sensitive: true },
  { id: 'zk-get', group: 'ZK ownership', method: 'GET', path: '/zk/:id', summary: 'Read zone set' },
  { id: 'zk-roots-list', group: 'ZK ownership', method: 'GET', path: '/zk/:id/roots', summary: 'List ownership roots' },
  { id: 'zk-roots-create', group: 'ZK ownership', method: 'POST', path: '/zk/:id/roots', summary: 'Generate ownership root', body: '{"root_address":"<address>","merkle_root":"<root>","snapshot_cid":"<cid>","snapshot_hash":"<hash>","commitment_count":0}', sensitive: true },
  { id: 'zk-proofs-list', group: 'ZK ownership', method: 'GET', path: '/zk/:id/proofs', summary: 'List proof nullifiers' },
  { id: 'zk-proofs-create', group: 'ZK ownership', method: 'POST', path: '/zk/:id/proofs', summary: 'Record ownership proof verification', body: '{"nullifier_hash":"<hash>","root_version":1,"prover":"<wallet>","proof_purpose":"<purpose>","disclosure_type":0}', sensitive: true },
  { id: 'zk-invalidate', group: 'ZK ownership', method: 'POST', path: '/zk/:id/invalidate/:version', summary: 'Invalidate ownership root version', sensitive: true },
  { id: 'spatial-near', group: 'Spatial & OSM', method: 'GET', path: '/spatial/parcels/near', summary: 'Find nearby parcels', query: '{"lon":11.5,"lat":3.8,"radius_m":1000,"limit":20}' },
  { id: 'spatial-zones', group: 'Spatial & OSM', method: 'GET', path: '/spatial/zones/stats', summary: 'Read spatial zone aggregates' },
  { id: 'spatial-zone-parcels', group: 'Spatial & OSM', method: 'GET', path: '/spatial/zones/:zone_id/parcels', summary: 'List parcels in spatial zone' },
  { id: 'spatial-parcel-stats', group: 'Spatial & OSM', method: 'GET', path: '/spatial/parcels/:id/stats', summary: 'Read parcel spatial metrics' },
  { id: 'geo-stats', group: 'Spatial & OSM', method: 'GET', path: '/geo/stats', summary: 'Read in-memory OSM coverage' },
  { id: 'geo-buildings', group: 'Spatial & OSM', method: 'GET', path: '/geo/buildings', summary: 'Query contextual OSM building footprints', query: '{"minx":11.49,"miny":3.84,"maxx":11.52,"maxy":3.86,"limit":100,"offset":0}' },
  { id: 'geo-roads', group: 'Spatial & OSM', method: 'GET', path: '/geo/nearest-roads', summary: 'Find nearest mapped roads', query: '{"lon":11.5,"lat":3.8,"limit":5}' },
  { id: 'geo-pois', group: 'Spatial & OSM', method: 'GET', path: '/geo/pois', summary: 'Find mapped points of interest', query: '{"lon":11.5,"lat":3.8,"radius":1000,"limit":20}' },
  { id: 'fusion-stats', group: 'Spatial & OSM', method: 'GET', path: '/fusion/stats', summary: 'Read PostGIS fusion status' },
  { id: 'fusion-roads', group: 'Spatial & OSM', method: 'GET', path: '/fusion/roads', summary: 'Query ingested road segments', query: '{"minx":11.49,"miny":3.84,"maxx":11.52,"maxy":3.86}' },
  { id: 'fusion-pois', group: 'Spatial & OSM', method: 'GET', path: '/fusion/pois', summary: 'Query ingested POIs', query: '{"minx":11.49,"miny":3.84,"maxx":11.52,"maxy":3.86}' },
  { id: 'fusion-ingest', group: 'Spatial & OSM', method: 'POST', path: '/fusion/ingest', summary: 'Ingest OSM data into PostGIS', sensitive: true },
  { id: 'fusion-reachability', group: 'Spatial & OSM', method: 'POST', path: '/fusion/reachability', summary: 'Analyze road access for geometry', body: '{"parcel_id":"0000000000000000000000000000000000000000000000000000000000000000","geometry":{"type":"Polygon","coordinates":[[[11.5,3.8],[11.5001,3.8],[11.5001,3.8001],[11.5,3.8001],[11.5,3.8]]]}}', mutates: false },
  { id: 'pilot-zones', group: 'Pilot zones & evidence', method: 'GET', path: '/pilot-zones', summary: 'List pilot zones' },
  { id: 'pilot-zone-create', group: 'Pilot zones & evidence', method: 'POST', path: '/pilot-zones', summary: 'Create pilot zone', body: '{"name":"<name>","description":"<description>","geometry":{"type":"Polygon","coordinates":[]}}' },
  { id: 'pilot-zone-get', group: 'Pilot zones & evidence', method: 'GET', path: '/pilot-zones/:id', summary: 'Read pilot zone' },
  { id: 'pilot-zone-assets', group: 'Pilot zones & evidence', method: 'GET', path: '/pilot-zones/:id/assets', summary: 'List photogrammetry assets' },
  { id: 'pilot-zone-asset-create', group: 'Pilot zones & evidence', method: 'POST', path: '/pilot-zones/:id/assets', summary: 'Register photogrammetry asset', body: '{"asset_type":"orthomosaic","name":"<name>","format":"GeoTIFF","resolution_m":0.1}', sensitive: true },
  { id: 'world-registries', group: 'World registry', method: 'GET', path: '/world-registry', summary: 'List world registries' },
  { id: 'world-registry-create', group: 'World registry', method: 'POST', path: '/world-registry', summary: 'Create world registry', body: '{"pubkey":"<address>","country_code":"CM","authority":"<wallet>"}', sensitive: true },
  { id: 'world-registry-get', group: 'World registry', method: 'GET', path: '/world-registry/:pubkey', summary: 'Read world registry' },
  { id: 'world-allocations', group: 'World registry', method: 'GET', path: '/world-registry/:pubkey/allocations', summary: 'List registry allocations' },
  { id: 'world-allocation-create', group: 'World registry', method: 'POST', path: '/world-registry/:pubkey/allocations', summary: 'Create registry allocation', body: '{"country_code":"CM","authority":"<wallet>"}', sensitive: true },
  { id: 'world-genesis-list', group: 'World registry', method: 'GET', path: '/world-registry/genesis-requests', summary: 'List genesis requests' },
  { id: 'world-genesis-get', group: 'World registry', method: 'GET', path: '/world-registry/genesis-requests/:country_code', summary: 'Read country genesis request' },
  { id: 'recovery-activities', group: 'Recovery & credentials', method: 'GET', path: '/recovery/activities', summary: 'List recovery activities' },
  { id: 'recovery-activity-create', group: 'Recovery & credentials', method: 'POST', path: '/recovery/activities', summary: 'Record validator recovery activity', body: '{"registry_pubkey":"<address>","validator_pubkey":"<address>","activity_type":"<type>"}', sensitive: true },
  { id: 'recovery-activity-get', group: 'Recovery & credentials', method: 'GET', path: '/recovery/activities/:registry_pubkey/:validator_pubkey', summary: 'Read validator recovery activity' },
  { id: 'recovery-injections', group: 'Recovery & credentials', method: 'GET', path: '/recovery/emergency-injections', summary: 'List emergency injections' },
  { id: 'recovery-injection-create', group: 'Recovery & credentials', method: 'POST', path: '/recovery/emergency-injections', summary: 'Queue emergency injection', body: '{"registry_pubkey":"<address>","validator_pubkey":"<address>","reason":"<reason>"}', sensitive: true },
  { id: 'recovery-injection-get', group: 'Recovery & credentials', method: 'GET', path: '/recovery/emergency-injections/:id', summary: 'Read emergency injection' },
  { id: 'credentials-requests', group: 'Recovery & credentials', method: 'GET', path: '/credentials/requests', summary: 'List threshold credential requests' },
  { id: 'credentials-request-create', group: 'Recovery & credentials', method: 'POST', path: '/credentials/requests', summary: 'Create threshold credential request', body: '{"credential_pubkey":"<address>","subject":"<wallet>"}', sensitive: true },
  { id: 'credentials-finalize', group: 'Recovery & credentials', method: 'POST', path: '/credentials/finalize', summary: 'Finalize threshold credential', body: '{"credential_pubkey":"<address>"}', sensitive: true },
  { id: 'credentials-list', group: 'Recovery & credentials', method: 'GET', path: '/credentials', summary: 'List threshold credentials' },
  { id: 'credentials-get', group: 'Recovery & credentials', method: 'GET', path: '/credentials/:credential_pubkey', summary: 'Read threshold credential' },
  { id: 'credentials-nullify', group: 'Recovery & credentials', method: 'POST', path: '/credentials/nullify', summary: 'Nullify threshold credential', body: '{"nullifier_hash":"<hash>","credential_pubkey":"<address>"}', sensitive: true },
  { id: 'credentials-nullifiers', group: 'Recovery & credentials', method: 'GET', path: '/credentials/nullifiers', summary: 'List threshold credential nullifiers' },
  { id: 'evidence-list', group: 'Pilot zones & evidence', method: 'GET', path: '/evidence', summary: 'List uploaded evidence metadata' },
  { id: 'evidence-get', group: 'Pilot zones & evidence', method: 'GET', path: '/evidence/:id', summary: 'Read evidence upload metadata' },
  { id: 'evidence-upload', group: 'Pilot zones & evidence', method: 'POST', path: '/evidence/upload', summary: 'Upload evidence file as multipart form data', sensitive: true, disabledReason: 'Multipart upload is not enabled in the JSON workbench. The API route expects signed request headers; use a trusted server-side uploader until wallet-key verification is implemented.' },
  { id: 'tx-prepare', group: 'Transaction preparation', method: 'POST', path: '/tx/prepare', summary: 'Prepare unsigned instruction payload', body: '{"type":"create_claim","parcel":"<base58>","claim_id":"<64-hex>","claim_type":0,"content_hash":"<64-hex>","required_attestations":1}', sensitive: true, disabledReason: 'Disabled: the current backend returns placeholder instruction data. Do not sign or submit its response.' },
]

export const BACKEND_GROUPS = [...new Set(BACKEND_OPERATIONS.map((operation) => operation.group))]
